/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ThreadParticipant` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client";
import type * as $Enums from "../enums.ts";
import type * as Prisma from "../internal/prismaNamespace.ts";

/**
 * Model ThreadParticipant
 *
 */
export type ThreadParticipantModel =
  runtime.Types.Result.DefaultSelection<Prisma.$ThreadParticipantPayload>;

export type AggregateThreadParticipant = {
  _count: ThreadParticipantCountAggregateOutputType | null;
  _avg: ThreadParticipantAvgAggregateOutputType | null;
  _sum: ThreadParticipantSumAggregateOutputType | null;
  _min: ThreadParticipantMinAggregateOutputType | null;
  _max: ThreadParticipantMaxAggregateOutputType | null;
};

export type ThreadParticipantAvgAggregateOutputType = {
  id: number | null;
  threadId: number | null;
  userId: number | null;
};

export type ThreadParticipantSumAggregateOutputType = {
  id: number | null;
  threadId: number | null;
  userId: number | null;
};

export type ThreadParticipantMinAggregateOutputType = {
  id: number | null;
  threadId: number | null;
  userId: number | null;
};

export type ThreadParticipantMaxAggregateOutputType = {
  id: number | null;
  threadId: number | null;
  userId: number | null;
};

export type ThreadParticipantCountAggregateOutputType = {
  id: number;
  threadId: number;
  userId: number;
  _all: number;
};

export type ThreadParticipantAvgAggregateInputType = {
  id?: true;
  threadId?: true;
  userId?: true;
};

export type ThreadParticipantSumAggregateInputType = {
  id?: true;
  threadId?: true;
  userId?: true;
};

export type ThreadParticipantMinAggregateInputType = {
  id?: true;
  threadId?: true;
  userId?: true;
};

export type ThreadParticipantMaxAggregateInputType = {
  id?: true;
  threadId?: true;
  userId?: true;
};

export type ThreadParticipantCountAggregateInputType = {
  id?: true;
  threadId?: true;
  userId?: true;
  _all?: true;
};

export type ThreadParticipantAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ThreadParticipant to aggregate.
   */
  where?: Prisma.ThreadParticipantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThreadParticipants to fetch.
   */
  orderBy?:
    | Prisma.ThreadParticipantOrderByWithRelationInput
    | Prisma.ThreadParticipantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ThreadParticipantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThreadParticipants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThreadParticipants.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ThreadParticipants
   **/
  _count?: true | ThreadParticipantCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ThreadParticipantAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ThreadParticipantSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ThreadParticipantMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ThreadParticipantMaxAggregateInputType;
};

export type GetThreadParticipantAggregateType<
  T extends ThreadParticipantAggregateArgs,
> = {
  [P in keyof T & keyof AggregateThreadParticipant]: P extends
    | "_count"
    | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateThreadParticipant[P]>
    : Prisma.GetScalarType<T[P], AggregateThreadParticipant[P]>;
};

export type ThreadParticipantGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ThreadParticipantWhereInput;
  orderBy?:
    | Prisma.ThreadParticipantOrderByWithAggregationInput
    | Prisma.ThreadParticipantOrderByWithAggregationInput[];
  by:
    | Prisma.ThreadParticipantScalarFieldEnum[]
    | Prisma.ThreadParticipantScalarFieldEnum;
  having?: Prisma.ThreadParticipantScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ThreadParticipantCountAggregateInputType | true;
  _avg?: ThreadParticipantAvgAggregateInputType;
  _sum?: ThreadParticipantSumAggregateInputType;
  _min?: ThreadParticipantMinAggregateInputType;
  _max?: ThreadParticipantMaxAggregateInputType;
};

export type ThreadParticipantGroupByOutputType = {
  id: number;
  threadId: number;
  userId: number;
  _count: ThreadParticipantCountAggregateOutputType | null;
  _avg: ThreadParticipantAvgAggregateOutputType | null;
  _sum: ThreadParticipantSumAggregateOutputType | null;
  _min: ThreadParticipantMinAggregateOutputType | null;
  _max: ThreadParticipantMaxAggregateOutputType | null;
};

type GetThreadParticipantGroupByPayload<
  T extends ThreadParticipantGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ThreadParticipantGroupByOutputType, T["by"]> & {
      [P in keyof T &
        keyof ThreadParticipantGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], ThreadParticipantGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], ThreadParticipantGroupByOutputType[P]>;
    }
  >
>;

export type ThreadParticipantWhereInput = {
  AND?:
    | Prisma.ThreadParticipantWhereInput
    | Prisma.ThreadParticipantWhereInput[];
  OR?: Prisma.ThreadParticipantWhereInput[];
  NOT?:
    | Prisma.ThreadParticipantWhereInput
    | Prisma.ThreadParticipantWhereInput[];
  id?: Prisma.IntFilter<"ThreadParticipant"> | number;
  threadId?: Prisma.IntFilter<"ThreadParticipant"> | number;
  userId?: Prisma.IntFilter<"ThreadParticipant"> | number;
  thread?: Prisma.XOR<
    Prisma.ThreadScalarRelationFilter,
    Prisma.ThreadWhereInput
  >;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
};

export type ThreadParticipantOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  threadId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  thread?: Prisma.ThreadOrderByWithRelationInput;
  user?: Prisma.UserOrderByWithRelationInput;
};

export type ThreadParticipantWhereUniqueInput = Prisma.AtLeast<
  {
    id?: number;
    AND?:
      | Prisma.ThreadParticipantWhereInput
      | Prisma.ThreadParticipantWhereInput[];
    OR?: Prisma.ThreadParticipantWhereInput[];
    NOT?:
      | Prisma.ThreadParticipantWhereInput
      | Prisma.ThreadParticipantWhereInput[];
    threadId?: Prisma.IntFilter<"ThreadParticipant"> | number;
    userId?: Prisma.IntFilter<"ThreadParticipant"> | number;
    thread?: Prisma.XOR<
      Prisma.ThreadScalarRelationFilter,
      Prisma.ThreadWhereInput
    >;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  },
  "id"
>;

export type ThreadParticipantOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  threadId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  _count?: Prisma.ThreadParticipantCountOrderByAggregateInput;
  _avg?: Prisma.ThreadParticipantAvgOrderByAggregateInput;
  _max?: Prisma.ThreadParticipantMaxOrderByAggregateInput;
  _min?: Prisma.ThreadParticipantMinOrderByAggregateInput;
  _sum?: Prisma.ThreadParticipantSumOrderByAggregateInput;
};

export type ThreadParticipantScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.ThreadParticipantScalarWhereWithAggregatesInput
    | Prisma.ThreadParticipantScalarWhereWithAggregatesInput[];
  OR?: Prisma.ThreadParticipantScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.ThreadParticipantScalarWhereWithAggregatesInput
    | Prisma.ThreadParticipantScalarWhereWithAggregatesInput[];
  id?: Prisma.IntWithAggregatesFilter<"ThreadParticipant"> | number;
  threadId?: Prisma.IntWithAggregatesFilter<"ThreadParticipant"> | number;
  userId?: Prisma.IntWithAggregatesFilter<"ThreadParticipant"> | number;
};

export type ThreadParticipantCreateInput = {
  thread: Prisma.ThreadCreateNestedOneWithoutParticipantsInput;
  user: Prisma.UserCreateNestedOneWithoutThreadsInput;
};

export type ThreadParticipantUncheckedCreateInput = {
  id?: number;
  threadId: number;
  userId: number;
};

export type ThreadParticipantUpdateInput = {
  thread?: Prisma.ThreadUpdateOneRequiredWithoutParticipantsNestedInput;
  user?: Prisma.UserUpdateOneRequiredWithoutThreadsNestedInput;
};

export type ThreadParticipantUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  threadId?: Prisma.IntFieldUpdateOperationsInput | number;
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ThreadParticipantCreateManyInput = {
  id?: number;
  threadId: number;
  userId: number;
};

export type ThreadParticipantUpdateManyMutationInput = {};

export type ThreadParticipantUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  threadId?: Prisma.IntFieldUpdateOperationsInput | number;
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ThreadParticipantListRelationFilter = {
  every?: Prisma.ThreadParticipantWhereInput;
  some?: Prisma.ThreadParticipantWhereInput;
  none?: Prisma.ThreadParticipantWhereInput;
};

export type ThreadParticipantOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type ThreadParticipantCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  threadId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ThreadParticipantAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  threadId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ThreadParticipantMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  threadId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ThreadParticipantMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  threadId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ThreadParticipantSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  threadId?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ThreadParticipantCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutUserInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutUserInput
      >
    | Prisma.ThreadParticipantCreateWithoutUserInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ThreadParticipantCreateManyUserInputEnvelope;
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
};

export type ThreadParticipantUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutUserInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutUserInput
      >
    | Prisma.ThreadParticipantCreateWithoutUserInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ThreadParticipantCreateManyUserInputEnvelope;
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
};

export type ThreadParticipantUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutUserInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutUserInput
      >
    | Prisma.ThreadParticipantCreateWithoutUserInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutUserInput
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ThreadParticipantCreateManyUserInputEnvelope;
  set?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  disconnect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  delete?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  update?:
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutUserInput
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutUserInput
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.ThreadParticipantScalarWhereInput
    | Prisma.ThreadParticipantScalarWhereInput[];
};

export type ThreadParticipantUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutUserInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutUserInput
      >
    | Prisma.ThreadParticipantCreateWithoutUserInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutUserInput
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ThreadParticipantCreateManyUserInputEnvelope;
  set?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  disconnect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  delete?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  update?:
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutUserInput
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutUserInput
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutUserInput[];
  deleteMany?:
    | Prisma.ThreadParticipantScalarWhereInput
    | Prisma.ThreadParticipantScalarWhereInput[];
};

export type ThreadParticipantCreateNestedManyWithoutThreadInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutThreadInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput
      >
    | Prisma.ThreadParticipantCreateWithoutThreadInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput[];
  createMany?: Prisma.ThreadParticipantCreateManyThreadInputEnvelope;
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
};

export type ThreadParticipantUncheckedCreateNestedManyWithoutThreadInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutThreadInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput
      >
    | Prisma.ThreadParticipantCreateWithoutThreadInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput[];
  createMany?: Prisma.ThreadParticipantCreateManyThreadInputEnvelope;
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
};

export type ThreadParticipantUpdateManyWithoutThreadNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutThreadInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput
      >
    | Prisma.ThreadParticipantCreateWithoutThreadInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput[];
  upsert?:
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutThreadInput
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutThreadInput[];
  createMany?: Prisma.ThreadParticipantCreateManyThreadInputEnvelope;
  set?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  disconnect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  delete?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  update?:
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutThreadInput
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutThreadInput[];
  updateMany?:
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutThreadInput
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutThreadInput[];
  deleteMany?:
    | Prisma.ThreadParticipantScalarWhereInput
    | Prisma.ThreadParticipantScalarWhereInput[];
};

export type ThreadParticipantUncheckedUpdateManyWithoutThreadNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.ThreadParticipantCreateWithoutThreadInput,
        Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput
      >
    | Prisma.ThreadParticipantCreateWithoutThreadInput[]
    | Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput[];
  connectOrCreate?:
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput
    | Prisma.ThreadParticipantCreateOrConnectWithoutThreadInput[];
  upsert?:
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutThreadInput
    | Prisma.ThreadParticipantUpsertWithWhereUniqueWithoutThreadInput[];
  createMany?: Prisma.ThreadParticipantCreateManyThreadInputEnvelope;
  set?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  disconnect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  delete?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  connect?:
    | Prisma.ThreadParticipantWhereUniqueInput
    | Prisma.ThreadParticipantWhereUniqueInput[];
  update?:
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutThreadInput
    | Prisma.ThreadParticipantUpdateWithWhereUniqueWithoutThreadInput[];
  updateMany?:
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutThreadInput
    | Prisma.ThreadParticipantUpdateManyWithWhereWithoutThreadInput[];
  deleteMany?:
    | Prisma.ThreadParticipantScalarWhereInput
    | Prisma.ThreadParticipantScalarWhereInput[];
};

export type ThreadParticipantCreateWithoutUserInput = {
  thread: Prisma.ThreadCreateNestedOneWithoutParticipantsInput;
};

export type ThreadParticipantUncheckedCreateWithoutUserInput = {
  id?: number;
  threadId: number;
};

export type ThreadParticipantCreateOrConnectWithoutUserInput = {
  where: Prisma.ThreadParticipantWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ThreadParticipantCreateWithoutUserInput,
    Prisma.ThreadParticipantUncheckedCreateWithoutUserInput
  >;
};

export type ThreadParticipantCreateManyUserInputEnvelope = {
  data:
    | Prisma.ThreadParticipantCreateManyUserInput
    | Prisma.ThreadParticipantCreateManyUserInput[];
};

export type ThreadParticipantUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ThreadParticipantWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.ThreadParticipantUpdateWithoutUserInput,
    Prisma.ThreadParticipantUncheckedUpdateWithoutUserInput
  >;
  create: Prisma.XOR<
    Prisma.ThreadParticipantCreateWithoutUserInput,
    Prisma.ThreadParticipantUncheckedCreateWithoutUserInput
  >;
};

export type ThreadParticipantUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ThreadParticipantWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.ThreadParticipantUpdateWithoutUserInput,
    Prisma.ThreadParticipantUncheckedUpdateWithoutUserInput
  >;
};

export type ThreadParticipantUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ThreadParticipantScalarWhereInput;
  data: Prisma.XOR<
    Prisma.ThreadParticipantUpdateManyMutationInput,
    Prisma.ThreadParticipantUncheckedUpdateManyWithoutUserInput
  >;
};

export type ThreadParticipantScalarWhereInput = {
  AND?:
    | Prisma.ThreadParticipantScalarWhereInput
    | Prisma.ThreadParticipantScalarWhereInput[];
  OR?: Prisma.ThreadParticipantScalarWhereInput[];
  NOT?:
    | Prisma.ThreadParticipantScalarWhereInput
    | Prisma.ThreadParticipantScalarWhereInput[];
  id?: Prisma.IntFilter<"ThreadParticipant"> | number;
  threadId?: Prisma.IntFilter<"ThreadParticipant"> | number;
  userId?: Prisma.IntFilter<"ThreadParticipant"> | number;
};

export type ThreadParticipantCreateWithoutThreadInput = {
  user: Prisma.UserCreateNestedOneWithoutThreadsInput;
};

export type ThreadParticipantUncheckedCreateWithoutThreadInput = {
  id?: number;
  userId: number;
};

export type ThreadParticipantCreateOrConnectWithoutThreadInput = {
  where: Prisma.ThreadParticipantWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.ThreadParticipantCreateWithoutThreadInput,
    Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput
  >;
};

export type ThreadParticipantCreateManyThreadInputEnvelope = {
  data:
    | Prisma.ThreadParticipantCreateManyThreadInput
    | Prisma.ThreadParticipantCreateManyThreadInput[];
};

export type ThreadParticipantUpsertWithWhereUniqueWithoutThreadInput = {
  where: Prisma.ThreadParticipantWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.ThreadParticipantUpdateWithoutThreadInput,
    Prisma.ThreadParticipantUncheckedUpdateWithoutThreadInput
  >;
  create: Prisma.XOR<
    Prisma.ThreadParticipantCreateWithoutThreadInput,
    Prisma.ThreadParticipantUncheckedCreateWithoutThreadInput
  >;
};

export type ThreadParticipantUpdateWithWhereUniqueWithoutThreadInput = {
  where: Prisma.ThreadParticipantWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.ThreadParticipantUpdateWithoutThreadInput,
    Prisma.ThreadParticipantUncheckedUpdateWithoutThreadInput
  >;
};

export type ThreadParticipantUpdateManyWithWhereWithoutThreadInput = {
  where: Prisma.ThreadParticipantScalarWhereInput;
  data: Prisma.XOR<
    Prisma.ThreadParticipantUpdateManyMutationInput,
    Prisma.ThreadParticipantUncheckedUpdateManyWithoutThreadInput
  >;
};

export type ThreadParticipantCreateManyUserInput = {
  id?: number;
  threadId: number;
};

export type ThreadParticipantUpdateWithoutUserInput = {
  thread?: Prisma.ThreadUpdateOneRequiredWithoutParticipantsNestedInput;
};

export type ThreadParticipantUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  threadId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ThreadParticipantUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  threadId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ThreadParticipantCreateManyThreadInput = {
  id?: number;
  userId: number;
};

export type ThreadParticipantUpdateWithoutThreadInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutThreadsNestedInput;
};

export type ThreadParticipantUncheckedUpdateWithoutThreadInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ThreadParticipantUncheckedUpdateManyWithoutThreadInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ThreadParticipantSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    threadId?: boolean;
    userId?: boolean;
    thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["threadParticipant"]
>;

export type ThreadParticipantSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    threadId?: boolean;
    userId?: boolean;
    thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["threadParticipant"]
>;

export type ThreadParticipantSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    threadId?: boolean;
    userId?: boolean;
    thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs["result"]["threadParticipant"]
>;

export type ThreadParticipantSelectScalar = {
  id?: boolean;
  threadId?: boolean;
  userId?: boolean;
};

export type ThreadParticipantOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  "id" | "threadId" | "userId",
  ExtArgs["result"]["threadParticipant"]
>;
export type ThreadParticipantInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>;
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type ThreadParticipantIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>;
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type ThreadParticipantIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  thread?: boolean | Prisma.ThreadDefaultArgs<ExtArgs>;
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $ThreadParticipantPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: "ThreadParticipant";
  objects: {
    thread: Prisma.$ThreadPayload<ExtArgs>;
    user: Prisma.$UserPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: number;
      threadId: number;
      userId: number;
    },
    ExtArgs["result"]["threadParticipant"]
  >;
  composites: {};
};

export type ThreadParticipantGetPayload<
  S extends boolean | null | undefined | ThreadParticipantDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$ThreadParticipantPayload, S>;

export type ThreadParticipantCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  ThreadParticipantFindManyArgs,
  "select" | "include" | "distinct" | "omit"
> & {
  select?: ThreadParticipantCountAggregateInputType | true;
};

export interface ThreadParticipantDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["ThreadParticipant"];
    meta: { name: "ThreadParticipant" };
  };
  /**
   * Find zero or one ThreadParticipant that matches the filter.
   * @param {ThreadParticipantFindUniqueArgs} args - Arguments to find a ThreadParticipant
   * @example
   * // Get one ThreadParticipant
   * const threadParticipant = await prisma.threadParticipant.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ThreadParticipantFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ThreadParticipantFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ThreadParticipant that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ThreadParticipantFindUniqueOrThrowArgs} args - Arguments to find a ThreadParticipant
   * @example
   * // Get one ThreadParticipant
   * const threadParticipant = await prisma.threadParticipant.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ThreadParticipantFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      ThreadParticipantFindUniqueOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ThreadParticipant that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadParticipantFindFirstArgs} args - Arguments to find a ThreadParticipant
   * @example
   * // Get one ThreadParticipant
   * const threadParticipant = await prisma.threadParticipant.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ThreadParticipantFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ThreadParticipantFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ThreadParticipant that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadParticipantFindFirstOrThrowArgs} args - Arguments to find a ThreadParticipant
   * @example
   * // Get one ThreadParticipant
   * const threadParticipant = await prisma.threadParticipant.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ThreadParticipantFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      ThreadParticipantFindFirstOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ThreadParticipants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadParticipantFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ThreadParticipants
   * const threadParticipants = await prisma.threadParticipant.findMany()
   *
   * // Get first 10 ThreadParticipants
   * const threadParticipants = await prisma.threadParticipant.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const threadParticipantWithIdOnly = await prisma.threadParticipant.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ThreadParticipantFindManyArgs>(
    args?: Prisma.SelectSubset<T, ThreadParticipantFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >;

  /**
   * Create a ThreadParticipant.
   * @param {ThreadParticipantCreateArgs} args - Arguments to create a ThreadParticipant.
   * @example
   * // Create one ThreadParticipant
   * const ThreadParticipant = await prisma.threadParticipant.create({
   *   data: {
   *     // ... data to create a ThreadParticipant
   *   }
   * })
   *
   */
  create<T extends ThreadParticipantCreateArgs>(
    args: Prisma.SelectSubset<T, ThreadParticipantCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ThreadParticipants.
   * @param {ThreadParticipantCreateManyArgs} args - Arguments to create many ThreadParticipants.
   * @example
   * // Create many ThreadParticipants
   * const threadParticipant = await prisma.threadParticipant.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ThreadParticipantCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ThreadParticipantCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many ThreadParticipants and returns the data saved in the database.
   * @param {ThreadParticipantCreateManyAndReturnArgs} args - Arguments to create many ThreadParticipants.
   * @example
   * // Create many ThreadParticipants
   * const threadParticipant = await prisma.threadParticipant.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ThreadParticipants and only return the `id`
   * const threadParticipantWithIdOnly = await prisma.threadParticipant.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ThreadParticipantCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      ThreadParticipantCreateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a ThreadParticipant.
   * @param {ThreadParticipantDeleteArgs} args - Arguments to delete one ThreadParticipant.
   * @example
   * // Delete one ThreadParticipant
   * const ThreadParticipant = await prisma.threadParticipant.delete({
   *   where: {
   *     // ... filter to delete one ThreadParticipant
   *   }
   * })
   *
   */
  delete<T extends ThreadParticipantDeleteArgs>(
    args: Prisma.SelectSubset<T, ThreadParticipantDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ThreadParticipant.
   * @param {ThreadParticipantUpdateArgs} args - Arguments to update one ThreadParticipant.
   * @example
   * // Update one ThreadParticipant
   * const threadParticipant = await prisma.threadParticipant.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ThreadParticipantUpdateArgs>(
    args: Prisma.SelectSubset<T, ThreadParticipantUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ThreadParticipants.
   * @param {ThreadParticipantDeleteManyArgs} args - Arguments to filter ThreadParticipants to delete.
   * @example
   * // Delete a few ThreadParticipants
   * const { count } = await prisma.threadParticipant.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ThreadParticipantDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ThreadParticipantDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ThreadParticipants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadParticipantUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ThreadParticipants
   * const threadParticipant = await prisma.threadParticipant.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ThreadParticipantUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ThreadParticipantUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ThreadParticipants and returns the data updated in the database.
   * @param {ThreadParticipantUpdateManyAndReturnArgs} args - Arguments to update many ThreadParticipants.
   * @example
   * // Update many ThreadParticipants
   * const threadParticipant = await prisma.threadParticipant.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ThreadParticipants and only return the `id`
   * const threadParticipantWithIdOnly = await prisma.threadParticipant.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ThreadParticipantUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      ThreadParticipantUpdateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one ThreadParticipant.
   * @param {ThreadParticipantUpsertArgs} args - Arguments to update or create a ThreadParticipant.
   * @example
   * // Update or create a ThreadParticipant
   * const threadParticipant = await prisma.threadParticipant.upsert({
   *   create: {
   *     // ... data to create a ThreadParticipant
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ThreadParticipant we want to update
   *   }
   * })
   */
  upsert<T extends ThreadParticipantUpsertArgs>(
    args: Prisma.SelectSubset<T, ThreadParticipantUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__ThreadParticipantClient<
    runtime.Types.Result.GetResult<
      Prisma.$ThreadParticipantPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of ThreadParticipants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadParticipantCountArgs} args - Arguments to filter ThreadParticipants to count.
   * @example
   * // Count the number of ThreadParticipants
   * const count = await prisma.threadParticipant.count({
   *   where: {
   *     // ... the filter for the ThreadParticipants we want to count
   *   }
   * })
   **/
  count<T extends ThreadParticipantCountArgs>(
    args?: Prisma.Subset<T, ThreadParticipantCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<
            T["select"],
            ThreadParticipantCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ThreadParticipant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadParticipantAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ThreadParticipantAggregateArgs>(
    args: Prisma.Subset<T, ThreadParticipantAggregateArgs>,
  ): Prisma.PrismaPromise<GetThreadParticipantAggregateType<T>>;

  /**
   * Group by ThreadParticipant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ThreadParticipantGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ThreadParticipantGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ThreadParticipantGroupByArgs["orderBy"] }
      : { orderBy?: ThreadParticipantGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    "Field ",
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      ThreadParticipantGroupByArgs,
      OrderByArg
    > &
      InputErrors,
  ): {} extends InputErrors
    ? GetThreadParticipantGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ThreadParticipant model
   */
  readonly fields: ThreadParticipantFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ThreadParticipant.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ThreadParticipantClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise";
  thread<T extends Prisma.ThreadDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.ThreadDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__ThreadClient<
    | runtime.Types.Result.GetResult<
        Prisma.$ThreadPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__UserClient<
    | runtime.Types.Result.GetResult<
        Prisma.$UserPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ThreadParticipant model
 */
export interface ThreadParticipantFieldRefs {
  readonly id: Prisma.FieldRef<"ThreadParticipant", "Int">;
  readonly threadId: Prisma.FieldRef<"ThreadParticipant", "Int">;
  readonly userId: Prisma.FieldRef<"ThreadParticipant", "Int">;
}

// Custom InputTypes
/**
 * ThreadParticipant findUnique
 */
export type ThreadParticipantFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * Filter, which ThreadParticipant to fetch.
   */
  where: Prisma.ThreadParticipantWhereUniqueInput;
};

/**
 * ThreadParticipant findUniqueOrThrow
 */
export type ThreadParticipantFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * Filter, which ThreadParticipant to fetch.
   */
  where: Prisma.ThreadParticipantWhereUniqueInput;
};

/**
 * ThreadParticipant findFirst
 */
export type ThreadParticipantFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * Filter, which ThreadParticipant to fetch.
   */
  where?: Prisma.ThreadParticipantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThreadParticipants to fetch.
   */
  orderBy?:
    | Prisma.ThreadParticipantOrderByWithRelationInput
    | Prisma.ThreadParticipantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ThreadParticipants.
   */
  cursor?: Prisma.ThreadParticipantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThreadParticipants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThreadParticipants.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ThreadParticipants.
   */
  distinct?:
    | Prisma.ThreadParticipantScalarFieldEnum
    | Prisma.ThreadParticipantScalarFieldEnum[];
};

/**
 * ThreadParticipant findFirstOrThrow
 */
export type ThreadParticipantFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * Filter, which ThreadParticipant to fetch.
   */
  where?: Prisma.ThreadParticipantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThreadParticipants to fetch.
   */
  orderBy?:
    | Prisma.ThreadParticipantOrderByWithRelationInput
    | Prisma.ThreadParticipantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ThreadParticipants.
   */
  cursor?: Prisma.ThreadParticipantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThreadParticipants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThreadParticipants.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ThreadParticipants.
   */
  distinct?:
    | Prisma.ThreadParticipantScalarFieldEnum
    | Prisma.ThreadParticipantScalarFieldEnum[];
};

/**
 * ThreadParticipant findMany
 */
export type ThreadParticipantFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * Filter, which ThreadParticipants to fetch.
   */
  where?: Prisma.ThreadParticipantWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ThreadParticipants to fetch.
   */
  orderBy?:
    | Prisma.ThreadParticipantOrderByWithRelationInput
    | Prisma.ThreadParticipantOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ThreadParticipants.
   */
  cursor?: Prisma.ThreadParticipantWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ThreadParticipants from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ThreadParticipants.
   */
  skip?: number;
  distinct?:
    | Prisma.ThreadParticipantScalarFieldEnum
    | Prisma.ThreadParticipantScalarFieldEnum[];
};

/**
 * ThreadParticipant create
 */
export type ThreadParticipantCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * The data needed to create a ThreadParticipant.
   */
  data: Prisma.XOR<
    Prisma.ThreadParticipantCreateInput,
    Prisma.ThreadParticipantUncheckedCreateInput
  >;
};

/**
 * ThreadParticipant createMany
 */
export type ThreadParticipantCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ThreadParticipants.
   */
  data:
    | Prisma.ThreadParticipantCreateManyInput
    | Prisma.ThreadParticipantCreateManyInput[];
};

/**
 * ThreadParticipant createManyAndReturn
 */
export type ThreadParticipantCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * The data used to create many ThreadParticipants.
   */
  data:
    | Prisma.ThreadParticipantCreateManyInput
    | Prisma.ThreadParticipantCreateManyInput[];
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * ThreadParticipant update
 */
export type ThreadParticipantUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * The data needed to update a ThreadParticipant.
   */
  data: Prisma.XOR<
    Prisma.ThreadParticipantUpdateInput,
    Prisma.ThreadParticipantUncheckedUpdateInput
  >;
  /**
   * Choose, which ThreadParticipant to update.
   */
  where: Prisma.ThreadParticipantWhereUniqueInput;
};

/**
 * ThreadParticipant updateMany
 */
export type ThreadParticipantUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ThreadParticipants.
   */
  data: Prisma.XOR<
    Prisma.ThreadParticipantUpdateManyMutationInput,
    Prisma.ThreadParticipantUncheckedUpdateManyInput
  >;
  /**
   * Filter which ThreadParticipants to update
   */
  where?: Prisma.ThreadParticipantWhereInput;
  /**
   * Limit how many ThreadParticipants to update.
   */
  limit?: number;
};

/**
 * ThreadParticipant updateManyAndReturn
 */
export type ThreadParticipantUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * The data used to update ThreadParticipants.
   */
  data: Prisma.XOR<
    Prisma.ThreadParticipantUpdateManyMutationInput,
    Prisma.ThreadParticipantUncheckedUpdateManyInput
  >;
  /**
   * Filter which ThreadParticipants to update
   */
  where?: Prisma.ThreadParticipantWhereInput;
  /**
   * Limit how many ThreadParticipants to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * ThreadParticipant upsert
 */
export type ThreadParticipantUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * The filter to search for the ThreadParticipant to update in case it exists.
   */
  where: Prisma.ThreadParticipantWhereUniqueInput;
  /**
   * In case the ThreadParticipant found by the `where` argument doesn't exist, create a new ThreadParticipant with this data.
   */
  create: Prisma.XOR<
    Prisma.ThreadParticipantCreateInput,
    Prisma.ThreadParticipantUncheckedCreateInput
  >;
  /**
   * In case the ThreadParticipant was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.ThreadParticipantUpdateInput,
    Prisma.ThreadParticipantUncheckedUpdateInput
  >;
};

/**
 * ThreadParticipant delete
 */
export type ThreadParticipantDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
  /**
   * Filter which ThreadParticipant to delete.
   */
  where: Prisma.ThreadParticipantWhereUniqueInput;
};

/**
 * ThreadParticipant deleteMany
 */
export type ThreadParticipantDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ThreadParticipants to delete
   */
  where?: Prisma.ThreadParticipantWhereInput;
  /**
   * Limit how many ThreadParticipants to delete.
   */
  limit?: number;
};

/**
 * ThreadParticipant without action
 */
export type ThreadParticipantDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ThreadParticipant
   */
  select?: Prisma.ThreadParticipantSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ThreadParticipant
   */
  omit?: Prisma.ThreadParticipantOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ThreadParticipantInclude<ExtArgs> | null;
};
